# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c437e9cc2c539bf51e50f1a123cf1eadb7adffc6cd42cd9afa53019796ac6737f9f1c3afb316f95a7a2bbf900861cc07eac830220c74858b103c4ad9df2f170c

test:
  secret_key_base: 5ac003b3a45a6bde938a5c52962e6bdede25b2d1c7e9280e4efb5e8e18191354e9d6100b8bbe2b1702b3e69ac4100c065736972ec9916171fb39cf1db41630fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
